version: 2
jobs:
  build:
    docker:
      - image: williamyeh/ansible:ubuntu18.04

    steps:
      - checkout

      - run:
          name: Update environment
          command: 
            - ansible --version


      - run:
          name: Print the Current Time
          command: date
