version: 2
jobs:
  build:
    docker:
      - image: williamyeh/ansible:ubuntu18.04

    steps:
      - checkout

      - run:
          name: Run ansible role on environment
          command: ansible-playbook tests/test.yml


      - run:
          name: Print the Current Time
          command: date
